# Generated by Django 5.1.4 on 2024-12-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_videos', '0002_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
